[[redirects]]
  from = "/shop"
  to = "https://www.nutrishopusa.com/store-referral/718"
  
  from = "/mobile/"
  to = "/"
  
  from = "/locations/"
  to = "/"
  
  from = "/about-us/"
  to = "/"
  
  from = "/contact-us/"
  to = "/"
